import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { vitePrerenderPlugin } from "vite-plugin-prerender";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
  vitePrerenderPlugin({
      staticDir: "dist",
      routes: [
        "/",
        "/about",
        "/contact",
        "/treatments/iui",
        "/treatments/ivf-et",
        "/treatments/icsi",
        "/treatments/ivm",
        "/treatments/imsi",
        "/treatments/embryo-monitoring",
        "/treatments/laser-assisted-hatching",
        "/treatments/laparoscopy",
        "/treatments/endocrine",
        "/treatments/sonography",
        "/treatments/hsg-sono",
        "/treatments/oocyte-donation",
        "/treatments/embryo-donation",
        "/treatments/blastocyst-transfer",
        "/treatments/egg-donation",
        "/treatments/cryopreservation",
        "/treatments/semen-cryopreservation",
        "/treatments/oocyte-cryopreservation",
        "/treatments/mesa-microepididymal-sperm-aspiration",
        "/treatments/tesa-testicular-sperm-aspiration-cryopreservation",
        "/treatments/heavy-menstrual-bleeding",
        "/treatments/irregular-periods",
        "/treatments/menopause-management",
        "/treatments/pcos-pcod",
        "/treatments/cervical-cancer",
        "/treatments/ovarian-cancer",
        "/treatments/uterus-cancer",
        "/treatments/cesarean-section-delivery",
        "/treatments/high-bp-and-diabetes-in-pregnancy",
        "/treatments/normal-delivery",
        "/treatments/pretem-labour",
        "/treatments/recurrent-pregnancy-loss",
        "/treatments/ovarian-cyst-laparoscopic-surgery",
        "/treatments/fibroid-removal-laparoscopic-surgery",
        "/treatments/endometriosis-treatment",
        "/treatments/pap-smear-screening",
        "/treatments/breast-health-checkup",
        "/treatments/hpv-vaccination",
        "/treatments/mammography",
        "/book-appointment",
        "/gallery",
        "/patients-guide",
        "/in-news",
      ],
    }),
  ],
})
